/* eslint-disable @typescript-eslint/no-require-imports */
module.exports = {
  content: [
    './src/app/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
    './src/services/**/*.{js,ts,jsx,tsx}',
    './node_modules/@sk-web-gui/react/dist/**/*.js',
    './node_modules/@sk-web-gui/theme/dist/**/*.js',
    './node_modules/@sk-web-gui/badge/dist/**/*.js',
    './node_modules/@sk-web-gui/breadcrumb/dist/**/*.js',
    './node_modules/@sk-web-gui/button/dist/**/*.js',
    './node_modules/@sk-web-gui/card/dist/**/*.js',
    './node_modules/@sk-web-gui/chip/dist/**/*.js',
    './node_modules/@sk-web-gui/forms/dist/**/*.js',
    './node_modules/@sk-web-gui/icon/dist/**/*.js',
    './node_modules/@sk-web-gui/layout/dist/**/*.js',
    './node_modules/@sk-web-gui/menu-vertical/dist/**/*.js',
    './node_modules/@sk-web-gui/modal/dist/**/*.js',
    './node_modules/@sk-web-gui/pagination/dist/**/*.js',
    './node_modules/@sk-web-gui/searchfield/dist/**/*.js',
    './node_modules/@sk-web-gui/spinner/dist/**/*.js',
    './node_modules/@sk-web-gui/table/dist/**/*.js',
    './node_modules/@sk-web-gui/tabs/dist/**/*.js',
    './node_modules/@sk-web-gui/tooltip/dist/**/*.js',
    './node_modules/@sk-web-gui/utils/dist/**/*.js',
  ],
  darkMode: 'class',
  presets: [require('@sk-web-gui/core').preset()],
};
