services:
  backend:
    build:
      context: ./backend
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 3000
      API_BASE_URL: ${API_BASE_URL:-}
      CLIENT_KEY: ${CLIENT_KEY:-}
      CLIENT_SECRET: ${CLIENT_SECRET:-}
      BASE_URL_PREFIX: ${BASE_URL_PREFIX:-/api}
      LOG_FORMAT: ${LOG_FORMAT:-combined}
      LOG_DIR: /app/data/logs
      ORIGIN: ${ORIGIN:-}
      REDIRECT_URL: ${REDIRECT_URL:-}
      MUNICIPALITY_ID: ${MUNICIPALITY_ID:-2281}
    volumes:
      - data:/app/data
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3010/api}
    depends_on:
      - backend
volumes:
  data:
